meta_product_name: "Mochinari"
meta_title: "Mochinari - Turn kowai into kawaii"
meta_description: "Find and track snacks across Japan like a local. Never be afraid of the language barrier again!"
meta_image: "mochi-banner.jpg" # should exist in `app/assets/images/`